md frontend\D.O.C_Frontend\src\components\common
md frontend\D.O.C_Frontend\src\components\auth
md frontend\D.O.C_Frontend\src\components\camera
md frontend\D.O.C_Frontend\src\components\sideEffects
md frontend\D.O.C_Frontend\src\components\ageVerification
md frontend\D.O.C_Frontend\src\components\dosage
md frontend\D.O.C_Frontend\src\components\triage
md frontend\D.O.C_Frontend\src\components\research
md frontend\D.O.C_Frontend\src\components\logging
md frontend\D.O.C_Frontend\src\pages\auth
md frontend\D.O.C_Frontend\src\hooks
md frontend\D.O.C_Frontend\src\context
md frontend\D.O.C_Frontend\src\services
md frontend\D.O.C_Frontend\src\utils
md frontend\D.O.C_Frontend\src\styles
md frontend\D.O.C_Frontend\src\tests\components
md frontend\D.O.C_Frontend\src\tests\pages
md frontend\D.O.C_Frontend\src\tests\utils
